### ISSUE TITLE
Physical coordinates and id of hanging nodes

### ISSUE THREAD

**Issue by khorrami1** [lcw/P4estTypes.jl#45]
Is there a way to retrieve the physical coordinates and ID of hanging nodes using P4estTypes.jl functionalities? I am interested in obtaining the physical coordinates of nodes obtained from `P4estTypes.unsafe_element_nodes(lnodes(forest))`.

Additionally, the ID numbers for each corner are not unique, as shown in the vtk file created by `P4estTypes.savevtk`. I plan to use this package for my FEM implementation.

Thank you so much in advance.

**Comment by lcw** [comment]
The physical coordinates are not directly available.  You need to compute them yourself.  An example doing that can be found here https://github.com/HorribleSanity/Raven.jl/blob/971310fdb4a691281b33b0a6114f8cd2c4d1f01f/src/lobattocells.jl#L288-L359C3.

The ids given in `P4estTypes.savevtk` duplicate the points at the corners.  To get the mapping to the unique node numbers you need to use `P4estTypes.unsafe_element_nodes(lnodes(forest))`.
